services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=ftzWBxKo6AUiK-AqGSnwjWfp9iOst-RZKU4zLwSP
    networks:
      - app_network
      - keycloak_network
    depends_on:
      - api
      - keycloak
  api:
    container_name: fastapi_app
    image: jmsajib11/stage_auth:0.0.1  # Use your image
    restart: unless-stopped
    depends_on:
      app_postgres:
        condition: service_healthy
      redis:
        condition: service_started
      keycloak:
        condition: service_started
    networks:
      - app_network
      - keycloak_network
    command: uvicorn run:app --host 0.0.0.0 --port 8000

  app_postgres:
    image: postgres:15
    container_name: app_postgres
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak_postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Hostname and HTTPS configuration
      KC_HOSTNAME: keycloak.jmsajib.com
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_PROXY: edge

      # Optional: Production settings
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
      KC_HEALTH_ENABLED: "true"
    command:
      - start-dev
    depends_on:
      keycloak_postgres:
        condition: service_healthy
    networks:
      - keycloak_network

volumes:
  app_postgres_data:
    name: app_postgres_data
  keycloak_postgres_data:
    name: keycloak_postgres_data
  redis_data:
    name: app_redis_data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  app_network:
    name: app_network
  keycloak_network:
    name: keycloak_network
